name: lint

on: [push]

jobs:
  lint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - run: npm install

    - name: lint
      uses: icrawl/action-eslint@v1
      with:
        custom-glob: src

    - name: prettify
      uses: creyD/prettier_action@v3.1
      with:
        dry: True
        file_pattern: src/*.ts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
